### ISSUE TITLE
Add operation to snapshots

### ISSUE THREAD

**Issue by rdblue** [Netflix/iceberg#42]
Snapshots that are append-only can be aged off more aggressively than deletes because all data files must be tracked in the next snapshot. Adding an operation type and a summary to snapshot metadata would enable improvements to metadata cleanup operations.

**Comment by julienledem** [comment]
another interesting operation: new snapshot that contain the same data as the previous one (for example compaction)

**Comment by rdblue** [comment]
This issue has moved to the ASF repo: https://github.com/apache/incubator-iceberg/issues/34
