### ISSUE TITLE
Add prefix matching expression

### ISSUE THREAD

**Issue by rdblue** [Netflix/iceberg#49]
Some users have requested prefix matching or startsWith.

**Comment by Liorba** [comment]
@rdblue can please give a bit more context on this issue?
is this prefix matching on partition transformation?

**Comment by Liorba** [comment]
working on this!

**Comment by Liorba** [comment]
@rdblue I tried to implement the `startWith` expression and I struggle with the fact that there is not place in the code I can assume that I'm working with strings.
all other `Operation` implementation at least  in `BoundExpressionVisitor`, seem to rely on the comparator function implemented in `types`. which imply order.
startsWith should have to know that the literal and field types are both strings  and use implantation other than compare.
if I do it like this the code will not compile, how do you suggest i'll add this?

**Comment by rdblue** [comment]
I'd start with adding a new factory method in `Expressions` that accepts a String. That will create an unbound predicate with a String literal, so you know at least that type. An unbound predicate may still be invalid.

Binding is the process of looking up the column in a schema to validate that it is there and then updating the expression to work with that column's type. For other predicates, the literal is coerced to the correct type in `UnboundPredicate#bind` by calling the literal's [`to` method](https://github.com/Netflix/iceberg/blob/master/api/src/main/java/com/netflix/iceberg/expressions/Literal.java#L76-L95) and passing in the column type. But in this case, you'd update `bind` to handle the `startsWith` expression and validate that both the column and the literal are types supported by the predicate. The bound predicate that is created by `bind` guarantees that types are coherent and that operations can be performed on those types.

To implement the `startsWith` predicate in an evaluator, you'd add it to the bound expression visitor and add eval implementations. Those implementations will operate on the guarantees from the binding process.

You should also implement at least inclusive projection in the transforms, but I can help you with that when you're close to that problem.

**Comment by rdblue** [comment]
I've moved this issue to https://github.com/apache/incubator-iceberg/issues/31. Please continue discussion there. Thanks!
