### ISSUE TITLE
Publish all project artifacts independently

### ISSUE THREAD

**Issue by mccheah** [Netflix/iceberg#65]
Currently, Iceberg has to be imported by including the `iceberg-runtime` jar on the classpath. However, this is problematic for detecting version conflicts between Iceberg and projects that depend on it. Build systems typically include an option to resolve version conflicts between different dependent modules, or outright fail the build if such version conflicts are not resolved. Conflicts can be resolved by forcing a specific version. The `iceberg-runtime` jar bundles all of its dependencies without declaring their versions in its Maven pom, so version conflicts between Iceberg's bundled dependencies and the dependencies pulled in by Iceberg's clients cannot be detected until runtime.

The solution is just to publish all modules and their dependencies separately as well, so that users of Iceberg can depend on the modules and track the Maven dependency tree properly. For example, in my Gradle I want to be able to do this:

```
dependencies {
  runtime 'com.netflix.iceberg:iceberg-spark:0.3.2'
}
```

**Comment by rdblue** [comment]
The runtime Jar shouldn't publish it's dependencies because they are either compileOnly or shaded. That Jar is for dropping as-is into a Spark distribution.

If you need to depend on Iceberg, then you should be pulling in the modules individually, which you should already be able to do by depending on `com.netflix.iceberg:iceberg-core:0.3.2` or similar. Those are published with JitPack and you can follow the link in the README for info on how to add the repository.

I think that's exactly what you're asking for in this issue, right?

**Comment by mccheah** [comment]
I was trying `./gradlew publishToMavenLocal` to try some changes locally, but that wasn't publishing iceberg-spark and core.

**Comment by rdblue** [comment]
I think that might be because the 0.3.2 release is actually building version 0.3.1. Looks like that release was tagged 0.3.2, but the version wasn't updated in build.gradle so builds still create 0.3.1 artifacts. Can you check whether you see the 0.3.1 Jars locally?

**Comment by mccheah** [comment]
> Those are published with JitPack and you can follow the link in the README for info on how to add the repository.

A question here - I'm having trouble finding the JitPack publishing documentation for this project. The details of how that works and where we publish to isn't listed in https://github.com/Netflix/iceberg/blob/master/README.md and it isn't specified in gradle. I don't see any such link.

Can we add the link to `README.md`?

**Comment by rdblue** [comment]
There's a JitPack badge in the README and there are instructions at the link. I'm not sure how JitPack sets the version or if it makes changes to Gradle, so maybe we just need to test it out. That said, we'll probably move to maven-based publication in the near future so we shouldn't waste too much time worrying about it.

**Comment by mccheah** [comment]
Ah I see it now, thanks!
